basePath: /
definitions:
  responses.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
  description: '-'
  title: Documenting Whitebook API
  version: "1"
paths:
  /advertisement/{advertisementsId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /advertisement/create:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /advertisement/delete/{advertisementsId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /advertisement/update:
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /advertisements:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-preview-image/{bookPreviewImageId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-preview-image/create:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-preview-image/delete/{bookPreviewImageId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-preview-image/update:
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-preview-images:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-user-detail/{bookUserDetailId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-user-detail/create:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-user-detail/delete/{bookUserDetailId}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-user-detail/update:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book-user-details:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book/{bookId}:
    get:
      description: '-'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book/create:
    post:
      description: '-'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book/delete:
    delete:
      description: '-'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /book/update:
    patch:
      description: '-'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /books:
    get:
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /cart/{cartId}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /cart/create:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /cart/delete/{cartId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /cart/update:
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /carts:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /category/{categoryId}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /category/create:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /category/delete/{categoryId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /category/update:
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      security:
      - bearerToken: []
      summary: Get a list of books in the the store
  /login:
    post:
      consumes:
      - application/json
      description: ลงชื่อเข้าใช้ระบบ
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      summary: Login
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - application/json
      description: แก้ไขข้อมูลหนังสือ
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/responses.Response'
      tags:
      - Auth
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
